export const FIAT_CURRENCIES = [
  'usd/azn',
  'usd/rub',
  'usd/eur',
  'usd/ils',
  'usd/aed',
  'eur/azn',
  'eur/usd',
  'eur/rub',
  'eur/ils',
  'eur/aed',
  'azn/rub',
  'azn/usd',
  'azn/eur',
  'azn/ils',
  'azn/aed',
  'rub/azn',
  'rub/usd',
  'rub/eur',
  'rub/ils',
  'rub/aed',
  'ils/usd',
  'ils/eur',
  'ils/rub',
  'ils/azn',
  'ils/aed',
  'aed/usd',
  'aed/eur',
  'aed/rub',
  'aed/azn',
  'aed/ils',
];

export const CRYPTO_CURRENCIES = ['BTCUSDT', 'BNBUSDT', 'ETHUSDT'];
